<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NotificationSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('notifications')->truncate();
        // Real notifications are generated by application events (Sprint 2+).
        // This seeder intentionally leaves the table empty.
    }
}
